version: 0.2
 
phases:
  pre_build:
    commands:
      - echo In pre_build phase..
      - echo Current directory is $CODEBUILD_SRC_DIR
      - ls -la
  build:
    commands:
      - hugo -v --gc --minify
      - aws s3 sync ./public s3://$S3_WEBSITE_BUCKET
artifacts:
  files:
    - '**/*'
  base-directory: public
